[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
# Must match your Thunderstore team name exactly
namespace = "LJIndustries"
name = "SmartRepair"
versionNumber = "1.0.0"
description = "Repairs everything the moment you open a crafting station, and lets later stations repair gear from earlier ones."
websiteUrl = "https://github.com/3WiseStooges/SmartRepair"
containsNsfwContent = false

[package.dependencies]
"denikson-BepInExPack_Valheim" = "5.4.2350"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "./package/SmartRepair.dll"
target = "SmartRepair.dll"

[publish]
repository = "https://thunderstore.io"
communities = ["valheim"]

[publish.categories]
valheim = ["mods", "crafting", "client-side", "tweaks"]
